// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfo4Jmru-tIhOokg30cZQnvzD_3HsazkQ',
    appId: '1:913234530681:web:cefc5791eec248320e1fa8',
    messagingSenderId: '913234530681',
    projectId: 'lettus-65e26',
    authDomain: 'lettus-65e26.firebaseapp.com',
    storageBucket: 'lettus-65e26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1oDWLZaxdxil5-MBjBDubFhm3f9T0UG0',
    appId: '1:913234530681:android:c7e174c82cd46b2e0e1fa8',
    messagingSenderId: '913234530681',
    projectId: 'lettus-65e26',
    storageBucket: 'lettus-65e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKYgp0Tjo8cZattAi1OhVMhZR11MjjBo',
    appId: '1:913234530681:ios:99b75edbd4534bd70e1fa8',
    messagingSenderId: '913234530681',
    projectId: 'lettus-65e26',
    storageBucket: 'lettus-65e26.firebasestorage.app',
    iosBundleId: 'com.lettus.lettus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsKYgp0Tjo8cZattAi1OhVMhZR11MjjBo',
    appId: '1:913234530681:ios:99b75edbd4534bd70e1fa8',
    messagingSenderId: '913234530681',
    projectId: 'lettus-65e26',
    storageBucket: 'lettus-65e26.firebasestorage.app',
    iosBundleId: 'com.lettus.lettus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfo4Jmru-tIhOokg30cZQnvzD_3HsazkQ',
    appId: '1:913234530681:web:b3b1ae8f3e5c741f0e1fa8',
    messagingSenderId: '913234530681',
    projectId: 'lettus-65e26',
    authDomain: 'lettus-65e26.firebaseapp.com',
    storageBucket: 'lettus-65e26.firebasestorage.app',
  );
}
